# Generated by Django 3.2.7 on 2021-11-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bruh', max_length=25)),
                ('email', models.EmailField(default='No_EMAIL', max_length=254)),
            ],
        ),
    ]
