# Generated by Django 3.2.7 on 2021-12-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=12345, max_length=25),
        ),
    ]
