# Generated by Django 3.2.7 on 2021-12-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Event_id', models.AutoField(primary_key=True, serialize=False)),
                ('Event_name', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=50)),
                ('Dorm_name', models.CharField(max_length=25)),
                ('Date', models.CharField(max_length=10)),
            ],
        ),
    ]
