# Generated by Django 3.2.7 on 2021-12-14 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentAssistant',
            fields=[
                ('RA_id', models.AutoField(primary_key=True, serialize=False)),
                ('RA_name', models.CharField(max_length=40)),
                ('Title', models.CharField(default='Basic RA', max_length=20)),
                ('Description', models.CharField(default='Basic RA duties: roam around the halls', max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='Dorm_name',
        ),
        migrations.AddField(
            model_name='event',
            name='Dorm_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.dorm'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('time', models.DateField(auto_now_add=True)),
                ('Receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver', to='API.user')),
                ('Sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='API.user')),
            ],
        ),
        migrations.CreateModel(
            name='EventRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.event')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.user')),
            ],
        ),
    ]
