# Generated by Django 3.2.7 on 2021-12-14 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_message_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('Work_id', models.AutoField(primary_key=True, serialize=False)),
                ('Submit_time', models.DateField(auto_now=True)),
                ('End_time', models.DateField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('Building_requested', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='API.unit')),
                ('RA_assigned', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='RA_assigned', to='API.user')),
                ('Submitter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Submitter', to='API.user')),
            ],
        ),
    ]
