# Generated by Django 3.2.7 on 2021-12-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
