# Generated by Django 3.2.7 on 2021-12-15 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_workorder_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='RA_assigned',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='RA_assigned', to='API.user'),
        ),
    ]
