# Generated by Django 3.2.7 on 2021-12-15 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_workorder_ra_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='Submitter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Submitter', to='API.user'),
        ),
    ]
