# Generated by Django 3.2.7 on 2021-12-15 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_workorder_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver', to='API.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='Sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='API.user'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='Building_requested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.unit'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='RA_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='RA_assigned', to='API.user'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='Submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Submitter', to='API.user'),
        ),
    ]
